/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MarketConfig } from "./MarketConfig";
export type { MarketEvents } from "./MarketEvents";
export type { PredictionMarket } from "./PredictionMarket";
