/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../common";

export interface MarketEventsInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "BetClaimed"
      | "BetPlaced"
      | "BetRefunded"
      | "DepositClaimed"
      | "MarketCancelled"
      | "MarketClosed"
      | "MarketCreated"
      | "MarketResolved"
  ): EventFragment;
}

export namespace BetClaimedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [contentHash: string, user: string, amount: bigint];
  export interface OutputObject {
    contentHash: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    user: AddressLike,
    betType: boolean,
    amount: BigNumberish,
    totalYesPool: BigNumberish,
    totalNoPool: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    user: string,
    betType: boolean,
    amount: bigint,
    totalYesPool: bigint,
    totalNoPool: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    user: string;
    betType: boolean;
    amount: bigint;
    totalYesPool: bigint;
    totalNoPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetRefundedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [contentHash: string, user: string, amount: bigint];
  export interface OutputObject {
    contentHash: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositClaimedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    creator: string,
    amount: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCancelledEvent {
  export type InputTuple = [contentHash: BytesLike];
  export type OutputTuple = [contentHash: string];
  export interface OutputObject {
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketClosedEvent {
  export type InputTuple = [contentHash: BytesLike];
  export type OutputTuple = [contentHash: string];
  export interface OutputObject {
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    deadline: BigNumberish,
    creator: AddressLike,
    groupOwner: AddressLike
  ];
  export type OutputTuple = [
    contentHash: string,
    deadline: bigint,
    creator: string,
    groupOwner: string
  ];
  export interface OutputObject {
    contentHash: string;
    deadline: bigint;
    creator: string;
    groupOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    result: BigNumberish,
    totalYesPool: BigNumberish,
    totalNoPool: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    result: bigint,
    totalYesPool: bigint,
    totalNoPool: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    result: bigint;
    totalYesPool: bigint;
    totalNoPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MarketEvents extends BaseContract {
  connect(runner?: ContractRunner | null): MarketEvents;
  waitForDeployment(): Promise<this>;

  interface: MarketEventsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "BetClaimed"
  ): TypedContractEvent<
    BetClaimedEvent.InputTuple,
    BetClaimedEvent.OutputTuple,
    BetClaimedEvent.OutputObject
  >;
  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "BetRefunded"
  ): TypedContractEvent<
    BetRefundedEvent.InputTuple,
    BetRefundedEvent.OutputTuple,
    BetRefundedEvent.OutputObject
  >;
  getEvent(
    key: "DepositClaimed"
  ): TypedContractEvent<
    DepositClaimedEvent.InputTuple,
    DepositClaimedEvent.OutputTuple,
    DepositClaimedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCancelled"
  ): TypedContractEvent<
    MarketCancelledEvent.InputTuple,
    MarketCancelledEvent.OutputTuple,
    MarketCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketClosed"
  ): TypedContractEvent<
    MarketClosedEvent.InputTuple,
    MarketClosedEvent.OutputTuple,
    MarketClosedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;

  filters: {
    "BetClaimed(bytes32,address,uint256)": TypedContractEvent<
      BetClaimedEvent.InputTuple,
      BetClaimedEvent.OutputTuple,
      BetClaimedEvent.OutputObject
    >;
    BetClaimed: TypedContractEvent<
      BetClaimedEvent.InputTuple,
      BetClaimedEvent.OutputTuple,
      BetClaimedEvent.OutputObject
    >;

    "BetPlaced(bytes32,address,bool,uint256,uint256,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "BetRefunded(bytes32,address,uint256)": TypedContractEvent<
      BetRefundedEvent.InputTuple,
      BetRefundedEvent.OutputTuple,
      BetRefundedEvent.OutputObject
    >;
    BetRefunded: TypedContractEvent<
      BetRefundedEvent.InputTuple,
      BetRefundedEvent.OutputTuple,
      BetRefundedEvent.OutputObject
    >;

    "DepositClaimed(bytes32,address,uint256)": TypedContractEvent<
      DepositClaimedEvent.InputTuple,
      DepositClaimedEvent.OutputTuple,
      DepositClaimedEvent.OutputObject
    >;
    DepositClaimed: TypedContractEvent<
      DepositClaimedEvent.InputTuple,
      DepositClaimedEvent.OutputTuple,
      DepositClaimedEvent.OutputObject
    >;

    "MarketCancelled(bytes32)": TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;
    MarketCancelled: TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;

    "MarketClosed(bytes32)": TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;
    MarketClosed: TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;

    "MarketCreated(bytes32,uint256,address,address)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(bytes32,uint8,uint256,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
  };
}
