/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MarketManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelMarket"
      | "createMarket"
      | "marketList"
      | "markets"
      | "placeBet"
      | "platformTreasury"
      | "resolveMarket"
      | "userBets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetPlaced"
      | "MarketCancelled"
      | "MarketClosed"
      | "MarketCreated"
      | "MarketResolved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelMarket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "markets", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userBets",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "marketList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userBets", data: BytesLike): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    user: AddressLike,
    betType: boolean,
    amount: BigNumberish,
    totalYesPool: BigNumberish,
    totalNoPool: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    user: string,
    betType: boolean,
    amount: bigint,
    totalYesPool: bigint,
    totalNoPool: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    user: string;
    betType: boolean;
    amount: bigint;
    totalYesPool: bigint;
    totalNoPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCancelledEvent {
  export type InputTuple = [contentHash: BytesLike];
  export type OutputTuple = [contentHash: string];
  export interface OutputObject {
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketClosedEvent {
  export type InputTuple = [contentHash: BytesLike];
  export type OutputTuple = [contentHash: string];
  export interface OutputObject {
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    deadline: BigNumberish,
    creator: AddressLike,
    groupOwner: AddressLike
  ];
  export type OutputTuple = [
    contentHash: string,
    deadline: bigint,
    creator: string,
    groupOwner: string
  ];
  export interface OutputObject {
    contentHash: string;
    deadline: bigint;
    creator: string;
    groupOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    result: BigNumberish,
    totalYesPool: BigNumberish,
    totalNoPool: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    result: bigint,
    totalYesPool: bigint,
    totalNoPool: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    result: bigint;
    totalYesPool: bigint;
    totalNoPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MarketManager extends BaseContract {
  connect(runner?: ContractRunner | null): MarketManager;
  waitForDeployment(): Promise<this>;

  interface: MarketManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelMarket: TypedContractMethod<
    [_contentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  createMarket: TypedContractMethod<
    [
      _contentHash: BytesLike,
      _deadline: BigNumberish,
      _groupOwner: AddressLike
    ],
    [string],
    "payable"
  >;

  marketList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  markets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        contentHash: string;
        deadline: bigint;
        totalYesPool: bigint;
        totalNoPool: bigint;
        creator: string;
        groupOwner: string;
        status: bigint;
        result: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;

  placeBet: TypedContractMethod<
    [_contentHash: BytesLike, _betType: boolean],
    [void],
    "payable"
  >;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  resolveMarket: TypedContractMethod<
    [_contentHash: BytesLike, _result: BigNumberish],
    [void],
    "nonpayable"
  >;

  userBets: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, boolean, boolean, boolean] & {
        amount: bigint;
        betType: boolean;
        betClaimed: boolean;
        refundClaimed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<[_contentHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      _contentHash: BytesLike,
      _deadline: BigNumberish,
      _groupOwner: AddressLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "marketList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        contentHash: string;
        deadline: bigint;
        totalYesPool: bigint;
        totalNoPool: bigint;
        creator: string;
        groupOwner: string;
        status: bigint;
        result: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [_contentHash: BytesLike, _betType: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [_contentHash: BytesLike, _result: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userBets"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, boolean, boolean, boolean] & {
        amount: bigint;
        betType: boolean;
        betClaimed: boolean;
        refundClaimed: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCancelled"
  ): TypedContractEvent<
    MarketCancelledEvent.InputTuple,
    MarketCancelledEvent.OutputTuple,
    MarketCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketClosed"
  ): TypedContractEvent<
    MarketClosedEvent.InputTuple,
    MarketClosedEvent.OutputTuple,
    MarketClosedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;

  filters: {
    "BetPlaced(bytes32,address,bool,uint256,uint256,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "MarketCancelled(bytes32)": TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;
    MarketCancelled: TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;

    "MarketClosed(bytes32)": TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;
    MarketClosed: TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;

    "MarketCreated(bytes32,uint256,address,address)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(bytes32,uint8,uint256,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
  };
}
