/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MarketData {
  export type MarketStruct = {
    contentHash: BytesLike;
    deadline: BigNumberish;
    totalYesPool: BigNumberish;
    totalNoPool: BigNumberish;
    creator: AddressLike;
    groupOwner: AddressLike;
    status: BigNumberish;
    result: BigNumberish;
    resolvedAt: BigNumberish;
  };

  export type MarketStructOutput = [
    contentHash: string,
    deadline: bigint,
    totalYesPool: bigint,
    totalNoPool: bigint,
    creator: string,
    groupOwner: string,
    status: bigint,
    result: bigint,
    resolvedAt: bigint
  ] & {
    contentHash: string;
    deadline: bigint;
    totalYesPool: bigint;
    totalNoPool: bigint;
    creator: string;
    groupOwner: string;
    status: bigint;
    result: bigint;
    resolvedAt: bigint;
  };

  export type UserBetStruct = {
    amount: BigNumberish;
    betType: boolean;
    betClaimed: boolean;
    refundClaimed: boolean;
  };

  export type UserBetStructOutput = [
    amount: bigint,
    betType: boolean,
    betClaimed: boolean,
    refundClaimed: boolean
  ] & {
    amount: bigint;
    betType: boolean;
    betClaimed: boolean;
    refundClaimed: boolean;
  };
}

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelMarket"
      | "claim"
      | "claimDeposit"
      | "claimedAmounts"
      | "createMarket"
      | "depositClaimed"
      | "distributeFees"
      | "getMarket"
      | "getMarketCount"
      | "getUserBet"
      | "hasClaimedBet"
      | "hasClaimedRefund"
      | "marketExists"
      | "marketList"
      | "markets"
      | "owner"
      | "placeBet"
      | "platformTreasury"
      | "refundCancelledBet"
      | "renounceOwnership"
      | "resolveMarket"
      | "setPlatformTreasury"
      | "transferOwnership"
      | "userBets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetClaimed"
      | "BetPlaced"
      | "BetRefunded"
      | "DepositClaimed"
      | "MarketCancelled"
      | "MarketClosed"
      | "MarketCreated"
      | "MarketResolved"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelMarket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "claimDeposit",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedAmounts",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositClaimed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeFees",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBet",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimedBet",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimedRefund",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "markets", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundCancelledBet",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userBets",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUserBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimedBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimedRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "marketList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundCancelledBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userBets", data: BytesLike): Result;
}

export namespace BetClaimedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [contentHash: string, user: string, amount: bigint];
  export interface OutputObject {
    contentHash: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    user: AddressLike,
    betType: boolean,
    amount: BigNumberish,
    totalYesPool: BigNumberish,
    totalNoPool: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    user: string,
    betType: boolean,
    amount: bigint,
    totalYesPool: bigint,
    totalNoPool: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    user: string;
    betType: boolean;
    amount: bigint;
    totalYesPool: bigint;
    totalNoPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetRefundedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [contentHash: string, user: string, amount: bigint];
  export interface OutputObject {
    contentHash: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositClaimedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    creator: string,
    amount: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCancelledEvent {
  export type InputTuple = [contentHash: BytesLike];
  export type OutputTuple = [contentHash: string];
  export interface OutputObject {
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketClosedEvent {
  export type InputTuple = [contentHash: BytesLike];
  export type OutputTuple = [contentHash: string];
  export interface OutputObject {
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    deadline: BigNumberish,
    creator: AddressLike,
    groupOwner: AddressLike
  ];
  export type OutputTuple = [
    contentHash: string,
    deadline: bigint,
    creator: string,
    groupOwner: string
  ];
  export interface OutputObject {
    contentHash: string;
    deadline: bigint;
    creator: string;
    groupOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    contentHash: BytesLike,
    result: BigNumberish,
    totalYesPool: BigNumberish,
    totalNoPool: BigNumberish
  ];
  export type OutputTuple = [
    contentHash: string,
    result: bigint,
    totalYesPool: bigint,
    totalNoPool: bigint
  ];
  export interface OutputObject {
    contentHash: string;
    result: bigint;
    totalYesPool: bigint;
    totalNoPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelMarket: TypedContractMethod<
    [_contentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<[_contentHash: BytesLike], [void], "nonpayable">;

  claimDeposit: TypedContractMethod<
    [_contentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  claimedAmounts: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  createMarket: TypedContractMethod<
    [
      _contentHash: BytesLike,
      _deadline: BigNumberish,
      _groupOwner: AddressLike
    ],
    [string],
    "payable"
  >;

  depositClaimed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  distributeFees: TypedContractMethod<
    [_contentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getMarket: TypedContractMethod<
    [_contentHash: BytesLike],
    [MarketData.MarketStructOutput],
    "view"
  >;

  getMarketCount: TypedContractMethod<[], [bigint], "view">;

  getUserBet: TypedContractMethod<
    [_contentHash: BytesLike, _user: AddressLike],
    [MarketData.UserBetStructOutput],
    "view"
  >;

  hasClaimedBet: TypedContractMethod<
    [_contentHash: BytesLike, _user: AddressLike],
    [boolean],
    "view"
  >;

  hasClaimedRefund: TypedContractMethod<
    [_contentHash: BytesLike, _user: AddressLike],
    [boolean],
    "view"
  >;

  marketExists: TypedContractMethod<
    [_contentHash: BytesLike],
    [boolean],
    "view"
  >;

  marketList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  markets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        contentHash: string;
        deadline: bigint;
        totalYesPool: bigint;
        totalNoPool: bigint;
        creator: string;
        groupOwner: string;
        status: bigint;
        result: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  placeBet: TypedContractMethod<
    [_contentHash: BytesLike, _betType: boolean],
    [void],
    "payable"
  >;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  refundCancelledBet: TypedContractMethod<
    [_contentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveMarket: TypedContractMethod<
    [_contentHash: BytesLike, _result: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userBets: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, boolean, boolean, boolean] & {
        amount: bigint;
        betType: boolean;
        betClaimed: boolean;
        refundClaimed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelMarket"
  ): TypedContractMethod<[_contentHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[_contentHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimDeposit"
  ): TypedContractMethod<[_contentHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimedAmounts"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      _contentHash: BytesLike,
      _deadline: BigNumberish,
      _groupOwner: AddressLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositClaimed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "distributeFees"
  ): TypedContractMethod<[_contentHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [_contentHash: BytesLike],
    [MarketData.MarketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserBet"
  ): TypedContractMethod<
    [_contentHash: BytesLike, _user: AddressLike],
    [MarketData.UserBetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimedBet"
  ): TypedContractMethod<
    [_contentHash: BytesLike, _user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimedRefund"
  ): TypedContractMethod<
    [_contentHash: BytesLike, _user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketExists"
  ): TypedContractMethod<[_contentHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "marketList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        contentHash: string;
        deadline: bigint;
        totalYesPool: bigint;
        totalNoPool: bigint;
        creator: string;
        groupOwner: string;
        status: bigint;
        result: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [_contentHash: BytesLike, _betType: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundCancelledBet"
  ): TypedContractMethod<[_contentHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [_contentHash: BytesLike, _result: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userBets"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, boolean, boolean, boolean] & {
        amount: bigint;
        betType: boolean;
        betClaimed: boolean;
        refundClaimed: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BetClaimed"
  ): TypedContractEvent<
    BetClaimedEvent.InputTuple,
    BetClaimedEvent.OutputTuple,
    BetClaimedEvent.OutputObject
  >;
  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "BetRefunded"
  ): TypedContractEvent<
    BetRefundedEvent.InputTuple,
    BetRefundedEvent.OutputTuple,
    BetRefundedEvent.OutputObject
  >;
  getEvent(
    key: "DepositClaimed"
  ): TypedContractEvent<
    DepositClaimedEvent.InputTuple,
    DepositClaimedEvent.OutputTuple,
    DepositClaimedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCancelled"
  ): TypedContractEvent<
    MarketCancelledEvent.InputTuple,
    MarketCancelledEvent.OutputTuple,
    MarketCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketClosed"
  ): TypedContractEvent<
    MarketClosedEvent.InputTuple,
    MarketClosedEvent.OutputTuple,
    MarketClosedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BetClaimed(bytes32,address,uint256)": TypedContractEvent<
      BetClaimedEvent.InputTuple,
      BetClaimedEvent.OutputTuple,
      BetClaimedEvent.OutputObject
    >;
    BetClaimed: TypedContractEvent<
      BetClaimedEvent.InputTuple,
      BetClaimedEvent.OutputTuple,
      BetClaimedEvent.OutputObject
    >;

    "BetPlaced(bytes32,address,bool,uint256,uint256,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "BetRefunded(bytes32,address,uint256)": TypedContractEvent<
      BetRefundedEvent.InputTuple,
      BetRefundedEvent.OutputTuple,
      BetRefundedEvent.OutputObject
    >;
    BetRefunded: TypedContractEvent<
      BetRefundedEvent.InputTuple,
      BetRefundedEvent.OutputTuple,
      BetRefundedEvent.OutputObject
    >;

    "DepositClaimed(bytes32,address,uint256)": TypedContractEvent<
      DepositClaimedEvent.InputTuple,
      DepositClaimedEvent.OutputTuple,
      DepositClaimedEvent.OutputObject
    >;
    DepositClaimed: TypedContractEvent<
      DepositClaimedEvent.InputTuple,
      DepositClaimedEvent.OutputTuple,
      DepositClaimedEvent.OutputObject
    >;

    "MarketCancelled(bytes32)": TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;
    MarketCancelled: TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;

    "MarketClosed(bytes32)": TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;
    MarketClosed: TypedContractEvent<
      MarketClosedEvent.InputTuple,
      MarketClosedEvent.OutputTuple,
      MarketClosedEvent.OutputObject
    >;

    "MarketCreated(bytes32,uint256,address,address)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(bytes32,uint8,uint256,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
